# Generated by Django 4.1.1 on 2022-09-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_balance', models.IntegerField()),
                ('receivable_balance', models.IntegerField()),
                ('cash_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.cashaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.incomecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('cash_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finances_record.cashentry')),
                ('income_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.incomeentry')),
            ],
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('cash_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finances_record.cashentry')),
                ('expense_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.expenseentry')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIncomeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.incomecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.expensecategory')),
            ],
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='monthly_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.monthlyincomesummary'),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.transaction'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='monthly_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.monthlyexpensesummary'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.transaction'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_record.transaction'),
        ),
    ]
