# Generated by Django 4.1.1 on 2022-09-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='cash_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_entry', to='finances_record.cashentry'),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='cash_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_entry', to='finances_record.cashentry'),
        ),
    ]
