# Generated by Django 4.1.1 on 2022-09-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='monthly_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='finances_record.monthlyexpensesummary'),
        ),
        migrations.AlterField(
            model_name='monthlyexpensesummary',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_expense_summaries', to='finances_record.expensecategory'),
        ),
    ]
