# Generated by Django 4.1.2 on 2022-10-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances_record', '0002_alter_cashentry_cash_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomecategory',
            old_name='target',
            new_name='budget',
        ),
    ]
