# Generated by Django 4.1.1 on 2022-09-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances_record', '0003_alter_cashentry_cash_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='cash_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='finances_record.cashentry'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='cash_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='finances_record.cashentry'),
        ),
    ]
